# These are supported funding model platforms

custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=BLC2P5B987NS2&item_name=Support+of+developments+that+are+mentioned+in+forked+Repo+README.md+files&currency_code=EUR&source=url
